### ISSUE TITLE
No Menu

### ISSUE THREAD

**Issue by CapttD** [Ian1971/mcbuilderwand#1]
I tried right-clicking the block but there's no menu that pops up. I have the wand in hand, am I missing something?

**Comment by Ian1971** [comment]
Since making this I found it won't work on PE. What version are you using?

**Comment by CapttD** [comment]
I'm using Bedrock 1.18 on Windows 10. I've been looking all over for a good
building buildingwand mod and yours is the first with a GUI menu.

**Comment by Ian1971** [comment]
It should work. Is experimental scripts enabled in the world?

**Comment by CapttD** [comment]
It is. hmm...
I can try and mess with it some more this afternoon.
There's only a few steps to it, lol. But I don't even think it registers
when I right click to select a block type. This no notification on screen
or chat.
My "tag" was set to builder due to the previous wand I was using. Maybe
that is it.

**Comment by Ian1971** [comment]
sounds like scripts are not running then. So probably expermental scripts need enabling

**Comment by Ian1971** [comment]
Also perhaps try a new world just to rule out something interfering with it

**Comment by CapttD** [comment]
I'll do that and report back.
Thanks for the support, you have a pretty awesome tool that was under my
radar

**Comment by Ian1971** [comment]
I've updated the mod as there was an issue with the latest minecraft. It should now work, but you need to choose "GameTest framework" in experimental options when creating a world.

**Comment by Ian1971** [comment]
Closing as is completed
